apiVersion: configs.flanksource.com/v1
kind: ScrapeConfig
metadata:
  name: {{ .Values.scraper.name }}
  labels:
    {{- include "azure.labels" . | nindent 4 }}
spec:
  azure:
  - subscriptionID: {{ .Values.subscriptionID | quote }}
    organisation: {{ .Values.organisation | quote }}
    tenantID: {{ .Values.tenantID | quote }}

    exclusions: {{ .Values.exclusions | toYaml | nindent 8 }}
    transform: {{ .Values.transform | toYaml | nindent 8 }}

    {{- if .Values.connection }}
    connection: {{.Values.connection | default ""}}
    {{- end }}

    {{- if and .Values.clientID .Values.clientSecret }}
    clientID: {{.Values.clientID | default dict | toYaml | nindent 6}}
    clientSecret: {{.Values.clientSecret |default dict | toYaml | nindent 6}}
    {{- end }}
