nameOverride: ""
fullnameOverride: ""
labels: {}
scraper:
  name: azure

subscriptionID: ''
organisation: ''
tenantID: ''

connectionDetails: {}
# connectionDetails:
#   connection: ''
#   clientID:
#     name: ''
#     value: ''
#     valueFrom:
#       serviceAccount: ''
#       helmRef:
#         key: ''
#         name: ''
#       configMapKeyRef:
#         key: ''
#         name: ''
#       secretKeyRef:
#         key: ''
#         name: ''

#   clientSecret:
#     name: ''
#     value: ''
#     valueFrom:
#       serviceAccount: ''
#       helmRef:
#         key: ''
#         name: ''
#       configMapKeyRef:
#         key: ''
#         name: ''
#       secretKeyRef:
#         key: ''
#         name: ''


exclusions:
# ActivityLogs is a list of operations to exclude from activity logs.
# Example:
# - Microsoft.ContainerService/managedClusters/listClusterAdminCredential/action
# - Microsoft.ContainerService/managedClusters/listClusterUserCredential/action
  activityLogs: []
