# yaml-language-server: $schema=values.schema.json

# @schema
# description: list of labels to add the Scrape config
# @schema
labels: {}
scraper:
  name: azure

# @schema
# required: true
# @schema
subscriptionID: ""
# @schema
# required: true
# @schema

organisation: ""
# @schema
# required: true
# @schema

tenantID: ""

connection: ''

clientID:
  name: ''
  value: ''
  valueFrom:
    serviceAccount: ''
    helmRef:
      key: ''
      name: ''
    configMapKeyRef:
      key: ''
      name: ''
    secretKeyRef:
      key: ''
      name: ''

clientSecret:
  name: ''
  value: ''
  valueFrom:
    serviceAccount: ''
    helmRef:
      key: ''
      name: ''
    configMapKeyRef:
      key: ''
      name: ''
    secretKeyRef:
      key: ''
      name: ''

transform:
  relationship:
    # Link AKS Cluster to Kubernetes Cluster
    - filter: config_class == 'KubernetesCluster'
      expr: |
        [{
          "type": "Kubernetes::Cluster",
          "labels": {
            "aks-nodeResourceGroup": config["properties"]["nodeResourceGroup"],
            "subscriptionID": labels["subscriptionID"]
          },
        }].toJSON()
    # Link Azure Virtual Machine Scale Sets to the Kubernetes Nodes
    - filter: config_class == 'Node'
      expr: |
        [{
          "type": "Kubernetes::Node",
          "labels": {
            "azure/vm-scale-set": name,
            "subscriptionID": labels["subscriptionID"]
          },
        }].toJSON()

exclusions:
  # @scheme
  # description: list of operations to exclude from activity logs
  # examples:
  #   - Microsoft.ContainerService/managedClusters/listClusterAdminCredential/action
  #   - Microsoft.ContainerService/managedClusters/listClusterUserCredential/action
  # type: array
  # @scema
  activityLogs: []
