nameOverride: ""
fullnameOverride: ""
labels: {}
scraper:
  name: azure

subscriptionID: ""
organisation: ""
tenantID: ""

# connection: ''
#
# clientID:
#   name: ''
#   value: ''
#   valueFrom:
#     serviceAccount: ''
#     helmRef:
#       key: ''
#       name: ''
#     configMapKeyRef:
#       key: ''
#       name: ''
#     secretKeyRef:
#       key: ''
#       name: ''

# clientSecret:
#   name: ''
#   value: ''
#   valueFrom:
#     serviceAccount: ''
#     helmRef:
#       key: ''
#       name: ''
#     configMapKeyRef:
#       key: ''
#       name: ''
#     secretKeyRef:
#       key: ''
#       name: ''

transform:
  relationship:
    # Link AKS Cluster to Kubernetes Cluster
    - filter: config_class == 'KubernetesCluster'
      expr: |
        [{
          "type": "Kubernetes::Cluster",
          "labels": {
            "aks-nodeResourceGroup": config["properties"]["nodeResourceGroup"],
            "subscriptionID": labels["subscriptionID"]
          },
        }].toJSON()
    # Link Azure Virtual Machine Scale Sets to the Kubernetes Nodes
    - filter: config_class == 'Node'
      expr: |
        [{
          "type": "Kubernetes::Node",
          "labels": {
            "azure/vm-scale-set": name,
            "subscriptionID": labels["subscriptionID"]
          },
        }].toJSON()

exclusions:
  # ActivityLogs is a list of operations to exclude from activity logs.
  # Example:
  # - Microsoft.ContainerService/managedClusters/listClusterAdminCredential/action
  # - Microsoft.ContainerService/managedClusters/listClusterUserCredential/action
  activityLogs: []
