# yaml-language-server: $schema=values.schema.json
---
global:
  # @schema
  # type: string
  # required: true
  # @schema
  # -- LLM connection: one of ollama, openai or anthropic
  llm_connection: ""

slack:
  # @schema
  # type: string
  # required: true
  # @schema
  # -- connection string for slack
  connection: ""

diagnose:
  # @schema
  # type: boolean
  # required: false
  # @schema
  # -- create a playbook that diagnoses cataloges
  enabled: true

  # @schema
  # required: false
  # type: array
  # items:
  #   type: object
  #   additionalProperties: true
  # @schema
  # -- selector the configs for the playbook resource
  selector:
    - name: "*"

  # @schema
  # type: string
  # required: false
  # @schema
  # -- Optional system prompt for the LLM. If not provided, a default prompt will be used.
  systemPrompt: ""

  notification:
    # @schema
    # type: boolean
    # required: false
    # @schema
    # -- create a playbook that diagnoses cataloges and send the diagnosis report to slack.
    enabled: true

    # @schema
    # type: string
    # required: false
    # @schema
    # -- Optional system prompt for the LLM. If not provided, a default prompt will be used.
    systemPrompt: ""
