# yaml-language-server: $schema=values.schema.json
# @schema
# type: string
# required: true
# @schema
# -- LLM connection: one of ollama, openai or anthropic
connection: ""

diagnose:
  # @schema
  # type: boolean
  # required: false
  # @schema
  # -- enable kubernetes diagnosing playbook
  enabled: true

  # @schema
  # type: string
  # required: true
  # @schema
  # -- name of the cluster
  cluster: ""

  # @schema
  # type: string
  # required: false
  # @schema
  # -- Optional system prompt for the LLM. If not provided, a default prompt will be used.
  systemPrompt: ""
