apiVersion: configs.flanksource.com/v1
kind: ScrapeConfig
metadata:
  name: {{ .Values.scraper.name }}
  labels:
    {{- include "kubernetes.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.scraper.schedule | quote }}
  kubernetes:
    - clusterName: {{ .Values.clusterName }}
      {{- with .Values.kubeconfig }}
      kubeconfig: {{ toYaml . | nindent 8}}
      {{- end}}
      exclusions:
        name:  {{ concat .Values.scraper.defaultExclusions.name .Values.scraper.exclusions.name | default  (list) |toYaml | nindent 10 }}
        kind:  {{ concat .Values.scraper.defaultExclusions.kind .Values.scraper.exclusions.kind | default  (list) | toYaml | nindent 10 }}
        labels:  {{ toYaml (merge .Values.scraper.defaultExclusions.labels .Values.scraper.exclusions.labels) | nindent 10 }}
        namespace:  {{ concat .Values.scraper.defaultExclusions.namespace .Values.scraper.exclusions.namespace | default  (list) | toYaml | nindent 10 }}
      relationships: {{ ( concat .Values.scraper.relationships .Values.scraper.defaultRelationships) | toYaml | nindent 8 }}
      transform: {{ .Values.scraper.transform | toYaml | nindent 8 }}
      event:  {{ .Values.scraper.event | toYaml | nindent 8 }}
  retention:
    changes: {{ .Values.scraper.retention.defaultChanges | toYaml | nindent 6 }}
    {{- with .Values.scraper.retention.changes }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.scraper.retention.staleItemAge }}
    staleItemAge: {{ . }}
    {{- end }}
