apiVersion: configs.flanksource.com/v1
kind: ScrapeConfig
metadata:
  name: {{ .Values.scraper.name }}
  labels:
    {{- include "kubernetes.labels" . | nindent 4 }}
spec:
  kubernetes:
    - clusterName: {{ .Values.scraper.clusterName }}
      exclusions: {{ toYaml (concat .Values.scraper.scrapeExclusions .Values.scraper.defaultScrapeExclusions) | nindent 8 }}
      relationships: {{ .Values.scraper.relationships | toYaml | nindent 8 }}
      transform: {{ .Values.scraper.transform | toYaml | nindent 8 }}
      event:
        exclusions: {{ .Values.scraper.eventExclusions | toYaml | nindent 10 }}
        severityKeywords: {{ .Values.scraper.severityKeywords | toYaml | nindent 10 }}
  retention:
    changes: {{ .Values.scraper.retention.changes | toYaml | nindent 6 }}
