{{- if and .Values.views.enabled .Values.views.cluster.enabled .Values.prometheus.connection }}
apiVersion: mission-control.flanksource.com/v1
kind: View
metadata:
  name: cluster-overview
  labels:
    {{- include "kubernetes.labels" . | nindent 4 }}
spec:
  display:
    title: Cluster
    icon: overview
    {{- if .Values.views.cluster.sidebar }}
    sidebar: true
    {{- end }}
    plugins:
      - configTab:
          types:
            - Kubernetes::Cluster
  panels:
    - name: Resources
      description: Count of resources grouped by type
      type: table
      query: SELECT * FROM resource_count_by_type
    - name: Total CPU Cores
      description: Total CPU cores available
      type: number
      query: SELECT value FROM cpu_cores_count
    - name: Total Memory Available
      description: Total memory available (GB)
      type: number
      number:
        unit: GB
        precision: 2
      query: SELECT value FROM memory_available_count
    - name: Current Memory Usage
      description: Current memory usage (GB)
      type: number
      number:
        unit: GB
      query: SELECT value FROM memory_usage_count
  queries:
    cpu_cores_count:
      prometheus:
        connection: {{ .Values.prometheus.connection }}
        query: |
          sum(kube_node_status_allocatable{resource="cpu"})
    memory_available_count:
      prometheus:
        connection: {{ .Values.prometheus.connection }}
        query: |
          sum(kube_node_status_allocatable{resource="memory"}) / 1024 / 1024 / 1024
    memory_usage_count:
      prometheus:
        connection: {{ .Values.prometheus.connection }}
        query: |
          sum(container_memory_working_set_bytes{container!="POD"}) / 1024 / 1024 / 1024
    resource_count_by_type:
      prometheus:
        connection: {{ .Values.prometheus.connection }}
        query: |
          (label_replace(count(kube_node_info), "resource_type", "Nodes", "", "")) or 
          (label_replace(count(kube_namespace_status_phase{phase="Active"}), "resource_type", "Namespaces", "", "")) or 
          (label_replace(count(kube_pod_status_phase{phase="Running"}), "resource_type", "Running Pods", "", "")) or 
          (label_replace(count(kube_deployment_status_replicas), "resource_type", "Deployments", "", "")) or 
          (label_replace(count(kube_statefulset_status_replicas), "resource_type", "StatefulSets", "", "")) or 
          (label_replace(count(kube_daemonset_status_number_ready), "resource_type", "DaemonSets", "", "")) or 
          (label_replace(count(kube_persistentvolume_info), "resource_type", "Persistent Volumes", "", "")) or 
          (label_replace(count(kube_persistentvolumeclaim_info), "resource_type", "Persistent Volume Claims", "", "")) or 
          (label_replace(count(kube_ingress_info), "resource_type", "Ingresses", "", "")) or 
          (label_replace(count(kube_cronjob_info), "resource_type", "CronJobs", "", ""))
{{- end }}