apiVersion: configs.flanksource.com/v1
kind: ScrapeConfig
metadata:
  name: {{ .Values.scraper.name }}
  labels:
    {{- include "aws.labels" . | nindent 4 }}
spec:
  aws:
  - compliance: {{ .Values.compliance }}

    {{- if .Values.costReporting.enabled }}
    cost_reporting:
      database: {{.Values.costReporting.database}}
      region: {{.Values.costReporting.region}}
      s3_bucket_path: {{.Values.costReporting.s3BucketPath}}
      table: {{.Values.costReporting.table}}
    {{- end }}

    include: {{ .Values.includeResources }}
    exclude: {{ .Values.excludeResources }}
    retention: {{ .Values.retention | toYaml | nindent 8 }}

    transform: {{ .Values.transform | toYaml | nindent 8 }}

    connection: "{{.Values.connection}}"
    accessKey: {{.Values.accessKey |toYaml | nindent 6}}
    secretKey: {{.Values.secretKey |toYaml | nindent 6}}
    region: {{.Values.region}}
    endpoint: "{{.Values.endpoint}}"
    skipTLSVerify: {{.Values.skipTLSVerify}}
    assumeRole: "{{.Values.assumeRole}}"
