apiVersion: configs.flanksource.com/v1
kind: ScrapeConfig
metadata:
  name: {{ .Values.scraper.name }}
  labels:
    {{- include "aws.labels" . | nindent 4 }}
spec:
  aws:
  - compliance: {{ .Values.compliance }}

    {{- if .Values.costReporting.enabled }}
    cost_reporting:
      database: {{.Values.costReporting.database}}
      region: {{.Values.costReporting.region}}
      s3_bucket_path: {{.Values.costReporting.s3BucketPath}}
      table: {{.Values.costReporting.table}}
    {{- end }}

    include: {{ .Values.includeResources }}
    exclude: {{ .Values.excludeResources }}
    retention: {{ .Values.retention | toYaml | nindent 8 }}

    transform: {{ .Values.transform | toYaml | nindent 8 }}

    {{ .Values.connectionDetails | toYaml | nindent 4 }}
