apiVersion: canaries.flanksource.com/v1
kind: Topology
metadata:
  name: {{ .Values.topology.name }}
spec:
  icon: aws
  type: Topology
  schedule: "@every 5m"
  components:
    - name: VPC
      icon: aws-vpc
      components:
      - name: VPC Component
        type: lookup
        lookup:
          catalog:
            - selector:
                - types: ['AWS::EC2::VPC']
              display:
                expr: |
                  dyn(results).map(c, {
                    'name': c.name,
                    'icon': 'aws-vpc',
                    'type': c.type,
                    'configs': [{'id': c.id}],
                    'externalID': c.external_id[0],
                    'status': c.status,
                    'status_reason': c.description,
                    'labels': c.labels,
                    'selectors': [{'types': ['AWS::EC2::Instance'], 'labelSelector': 'network='+c.external_id[0]}]
                  }).toJSON()

    - name: EC2
      icon: aws-ec2
      components:
      - name: EC2 Component
        type: lookup
        lookup:
          catalog:
            - selector:
                - types: ['AWS::EC2::Instance']
              display:
                expr: |
                  dyn(results).map(c, {
                    'name': c.external_id[0] + '/' + c.name,
                    'icon': 'aws-ec2',
                    'type': c.type,
                    'configs': [{'id': c.id}],
                    'status': c.status,
                    'status_reason': c.description,
                    'labels': c.labels,
                    'properties': [
                      {'name': 'NodeGroup', 'text': 'eksctl.io/v1alpha2/nodegroup-name' in c.labels ? c.labels['eksctl.io/v1alpha2/nodegroup-name'] : ''}
                    ],
                  }).toJSON()

    - name: EKS
      icon: aws-eks-cluster
      components:
      - name: EKS Component
        type: lookup
        lookup:
          catalog:
            - selector:
                - types: ['AWS::EKS::Cluster']
              display:
                expr: |
                  dyn(results).map(c, {
                    'name': c.name,
                    'icon': 'aws-eks-cluster',
                    'type': c.type,
                    'labels': c.labels,
                    'configs': [{'id': c.id}],
                    'status': c.status,
                    'status_reason': c.description,
                    'selectors': [{'types': ['AWS::EC2::Instance'], 'labelSelector': 'alpha.eksctl.io/cluster-name='+c.labels['alpha.eksctl.io/cluster-name']}]
                  }).toJSON()

    - name: ELB
      icon: aws-elb
      components:
      - name: ELB Component
        type: lookup
        lookup:
          catalog:
            - selector:
                - types: ['AWS::ElasticLoadBalancing::LoadBalancer', 'AWS::ElasticLoadBalancingV2::LoadBalancer']
              display:
                expr: |
                  dyn(results).map(c, {
                    'name': c.name,
                    'icon': 'aws-elb',
                    'type': c.type,
                    'configs': [{'id': c.id}],
                    'status': c.status,
                    'status_reason': c.description,
                    'labels': c.labels,
                  }).toJSON()
