# yaml-language-server: $schema=./values.schema.json
nameOverride: ""
fullnameOverride: ""
labels: {}
topologyName: flux

playbooks:
  enabled: true

  resume: true
  suspend: true
  reconcile: true
  updateHelmValues: true
  updateHelmChartVersion: true
