nameOverride: ""
fullnameOverride: ""
labels: {}

clusterName: kubernetes
prometheusURL: ''

topology:
  name: cluster
  schedule: "@every 5m"
  icon: kubernetes

scraper:
  name: kubernetes
  defaultScrapeExclusions:
    - APIService
    - PodMetrics
    - NodeMetrics
    - endpoints.discovery.k8s.io
    - endpointslices.discovery.k8s.io
    - leases.coordination.k8s.io
    - podmetrics.metrics.k8s.io
    - nodemetrics.metrics.k8s.io
    - controllerrevision
    - certificaterequest
    - orders.acme.cert-manager.io

  scrapeExclusions:
    - Secret
    - customresourcedefinition

  relationships:
    # FluxCD Helm relationships
    - name:
        label: 'helm.toolkit.fluxcd.io/name'
      namespace:
        label: 'helm.toolkit.fluxcd.io/namespace'
      kind:
        value: 'HelmRelease'
    # FluxCD Kustomize relationships
    - name:
        label: 'kustomize.toolkit.fluxcd.io/name'
      namespace:
        label: 'kustomize.toolkit.fluxcd.io/namespace'
      kind:
        value: 'Kustomization'

  eventExclusions:
    reason:
      - SuccessfulCreate
      - Created
      - DNSConfigForming

  transform:
    changes:
      exclude:
        - 'details.source.component == "canary-checker" && details.reason == "Failed"'
        - 'details.source.component == "canary-checker" && details.reason == "Succeeded"'

  severityKeywords:
   error:
     - failed
     - error
   warn:
     - backoff
     - nodeoutofmemory

  retention:
    changes:
      - name: ReconciliationSucceeded
        count: 10
