# yaml-language-server: $schema=./values.schema.json
nameOverride: ""
fullnameOverride: ""
labels: {}

clusterName: kubernetes
prometheusURL: ""
topology:
  name: cluster
  schedule: "@every 5m"
  icon: kubernetes

scraper:
  name: kubernetes
  schedule: "@every 5m"
  exclusions:
    name: []
    namespace: []
    kind: []
    labels: {}
  defaultExclusions:
    name: []
    namespace: []
    labels:
      canary-checker.flanksource.com/generated: "true"
    kind:
      - Secret
      - APIService
      - PodMetrics
      - NodeMetrics
      - endpoints.discovery.k8s.io
      - endpointslices.discovery.k8s.io
      - leases.coordination.k8s.io
      - podmetrics.metrics.k8s.io
      - nodemetrics.metrics.k8s.io
      - customresourcedefinition
      - controllerrevisions
      - certificaterequests
      - orders.acme.cert-manager.io

  relationships: []
  defaultRelationships:
    - kind:
        expr: "has(spec.claimRef) ? spec.claimRef.kind : ''"
      name:
        expr: "has(spec.claimRef) ? spec.claimRef.name : ''"
      namespace:
        expr: "has(spec.claimRef) ? spec.claimRef.namespace : ''"
    # FluxCD Helm relationships
    - name:
        label: "helm.toolkit.fluxcd.io/name"
      namespace:
        label: "helm.toolkit.fluxcd.io/namespace"
      kind:
        value: "HelmRelease"
    # FluxCD Kustomize relationships
    - name:
        label: "kustomize.toolkit.fluxcd.io/name"
      namespace:
        label: "kustomize.toolkit.fluxcd.io/namespace"
      kind:
        value: "Kustomization"
    # FluxCD Git relationships
    - name:
        expr: "has(spec.sourceRef) ? spec.sourceRef.name : '' "
      namespace:
        expr: "has(spec.sourceRef) && has(spec.sourceRef.namespace)  ? spec.sourceRef.namespace : metadata.namespace "
      kind:
        value: "GitRepository"

  event:
    exclusions:
      reason:
        - SuccessfulCreate
        - Created
        - DNSConfigForming

    severityKeywords:
      error:
        - failed
        - error
      warn:
        - backoff
        - nodeoutofmemory

  transform:
    changes:
      exclude:
        - 'config_type == "Kubernetes::Application" && details.message == "status.reconciledAt" && change_type == "diff" && details.involvedObject.apiVersion == "argoproj.io/v1alpha1"'
        - 'config_type == "Kubernetes::Endpoints" && details.message == "metadata.annotations.endpoints.kubernetes.io/last-change-trigger-time"'
        - 'config_type == "Kubernetes::Node" && details.message == "status.images"'
        - 'details.source.component == "canary-checker" && (change_type == "Failed" || change_type == "Pass")'

    relationship:
      # Link Pods to PVCs
      - filter: config_type == 'Kubernetes::Pod'
        expr: |
          config.spec.volumes.
            filter(item, has(item.persistentVolumeClaim)).
            map(item, {"type": "Kubernetes::PersistentVolumeClaim", "name": item.persistentVolumeClaim.claimName}).
            toJSON()

  retention:
    changes:
      - name: ReconciliationSucceeded
        count: 10
