nameOverride: ""
fullnameOverride: ""
labels: {}
scraperName: kubernetes
clusterName: kubernetes
scrapeExclusions:
  - Secret
  - ReplicaSet
  - APIService
  - PodMetrics
  - NodeMetrics
  - endpoints.discovery.k8s.io
  - endpointslices.discovery.k8s.io
  - leases.coordination.k8s.io
  - podmetrics.metrics.k8s.io
  - nodemetrics.metrics.k8s.io
  - customresourcedefinition
  - controllerrevision
  - certificaterequest
  - orders.acme.cert-manager.io

eventExclusions:
  - SuccessfulCreate
  - Created
  - DNSConfigForming

severityKeywords:
 error:
   - failed
   - error
 warn:
   - backoff
   - nodeoutofmemory

retention:
  changes:
    - name: ReconciliationSucceeded
      count: 10
