# yaml-language-server: $schema=https://raw.githubusercontent.com/flanksource/duty/main/schema/openapi/playbook.schema.json

{{- if and .Values.playbooks.enabled .Values.playbooks.cordonNode }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: kubernetes-cordon-node
spec:
  title: Cordon Node
  icon: k8s-node
  category: Kubernetes
  description: Cordons a node using kubectl
  configs:
    - agent: all
      types:
        - Kubernetes::Node

  runsOn:
    -  {{` "{{- if .agent }}{{.agent.id}}{{ else }}local{{ end }}" `}}

  actions:
    - name: kubectl cordon
      exec:
        {{- include "exec-action-connections" . | nindent 8}}
        script: kubectl cordon $(.config.name)
{{- end}}
