# yaml-language-server: $schema=https://raw.githubusercontent.com/flanksource/duty/main/schema/openapi/playbook.schema.json

{{- if and .Values.playbooks.enabled .Values.playbooks.createDeployment }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: kubernetes-create-deployment
spec:
  title: Create Deployment
  icon: k8s-deployment
  category: Kubernetes
  description: Create a new deployment
  parameters:
    - name: name
      label: Name

    - name: image
      label: Container Image

  configs:
    - agent: all
      types:
        - Kubernetes::Namespace
  actions:
    - name: Create Deployment
      exec:
        script: |
          # gotemplate: left-delim=$[[ right-delim=]]
          echo "Running on $(hostname)" >&2
          name=$[[.params.name]]
          ns=$[[.config.name]]
          kubectl create deployment $name --image=$[[.params.image]] -n $ns >&2
          kubectl annotate deployment $name -n $ns \
                  "mission-control/playbook=$[[.playbook.name]]" \
                  "mission-control/run=$[[.run.id]]" \
                  "mission-control/createdBy=$[[.user.name]]" >&2
          kubectl get deploy $name -n $ns -o json  | jq -r '.metadata.uid'

{{- end}}
