# yaml-language-server: $schema=https://raw.githubusercontent.com/flanksource/duty/main/schema/openapi/playbook.schema.json

{{- if and .Values.playbooks.enabled .Values.playbooks.podSnapshot }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: pod-snapshot
spec:
  title: Pod Snapshot
  category: Kubernetes
  description: Takes a snapshot of a pod using kubectl (logs, manifest and events)
  icon: add-snapshot
  configs:
    - agent: all
      types:
        - Kubernetes::Pod
  runsOn:
    -  {{` "{{- if .agent }}{{.agent.id}}{{ else }}local{{ end }}" `}}

  actions:
    - name: kubectl
      exec:
        {{- include "exec-action-connections" . | nindent 8}}
        script: |
          path="/tmp/pod-snapshot/$(.config.id)"
          rm -rf $path
          mkdir -p $path
          kubectl logs $(.config.name) -n $(.config.tags.namespace) > "$path/logs.txt"
          kubectl get pods $(.config.name) -n $(.config.tags.namespace) -o yaml > "$path/manifest.yaml"
          kubectl get events --field-selector=involvedObject.kind=Pod,involvedObject.name=$(.config.name) \
            -n $(.config.tags.namespace) > "$path/events.txt"
        artifacts:
          - path: '/tmp/pod-snapshot/$(.config.id)/*'
{{- end}}






