# yaml-language-server: $schema=https://raw.githubusercontent.com/flanksource/duty/main/schema/openapi/playbook.schema.json

{{- if and .Values.playbooks.enabled .Values.playbooks.requestNamespaceAccess }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: kubernetes-namespace-access
spec:
  title: Request Namespace Access
  icon: k8s-namespace
  category: Kubernetes
  description: Adds a Rolebinding to the given role
  parameters:
    - name: user
      label: User
    - name: expiry
      label: Expires after
      type: list
      properties:
        options:
          - label: "4 hours"
            value: '4h'
          - label: "8 hours"
            value: '8h'
          - label: "3 days"
            value: "3d"
          - label: "10 days"
            value: "10d"
          - label: "2 weeks"
            value: "14d"
          - label: "30 days"
            value: "30d"
          - label: "Indefinitely"
            value: "0"
    - name: role
      label: Role
      type: config
      properties:
        filter:
          - types:
              - Kubernetes::ClusterRole
  configs:
    - agent: all
      types:
        - Kubernetes::Namespace
  runsOn:
    -  {{` "{{- if .agent }}{{.agent.id}}{{ else }}local{{ end }}" `}}

  actions:
    - name: Create RoleBinding
      exec:
        connections:
          fromConfigItem: '$(.config.id)'
          {{- if .Values.connections.podIdentity }}
          eksPodIdentity: true
          {{- end }}
          {{- if .Values.connections.serviceAccount }}
          serviceAccount: true
          {{- end }}
        script: >-
          kubectl create rolebinding "playbook-$(.run.id)"
          --namespace=$(.config.name)
          --user=$(.params.user)
          --role=$(.params.role.name)
    - name: Clear Rolebinding
      if: 'success() && params.expiry != "0"'
      delay: "params.expiry"
      exec:
        connections:
          fromConfigItem: '$(.config.id)'
          {{- if .Values.connections.podIdentity }}
          eksPodIdentity: true
          {{- end }}
          {{- if .Values.connections.serviceAccount }}
          serviceAccount: true
          {{- end }}
        script: |
          kubectl delete rolebinding "playbook-$(.run.id)" --namespace=$(.config.name)
{{- end}}
