# yaml-language-server: $schema=https://raw.githubusercontent.com/flanksource/duty/main/schema/openapi/playbook.schema.json

{{- if and .Values.playbooks.enabled .Values.playbooks.restart }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: kubernetes-restart
spec:
  title: Restart
  icon: reload
  category: Kubernetes
  configs:
    - agent: all
      types:
        - Kubernetes::Deployment
        - Kubernetes::Statefulset
        - Kubernetes::DaemonSet

  runsOn:
    -  {{` "{{- if .agent }}{{.agent.id}}{{ else }}local{{ end }}" `}}

  actions:
    - name: Restart
      exec:
        connections:
          fromConfigItem: '$(.config.id)'
        script: |
          kubectl rollout restart -n $(.config.tags.namespace) $(.config.config_class)/$(.config.name)
{{- end}}
