{{- if and .Values.playbooks.enabled .Values.playbooks.updateHelmValues }}
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: update-helm-values
spec:
  title: Update helm values
  icon: todo-yash
  category: Flux
  configs:
    - types:
        - Kubernetes::HelmRelease

  parameters:
    - default: $(.config.config.spec.values | toJSON | json | toYAML)
      label: ""
      name: yamlInput
      properties:
        size: large
      type: code

  actions:
    - name: Update helm values
      exec:
        script: |
          kubectl patch helmrelease -n $(.config.tags.namespace) $(.config.name) -p '{"spec": {"values": $(.params.yamlInput | yaml | toJSON)}}'
{{- end}}
