---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: kustomize-create-namespace
spec:
  category: Flux
  description: Create a new namespace
  icon: namespace
  title: Create Namespace

  configs:
    - types:
        - Kubernetes::Kustomization
  parameters:
    - name: name
      label: Name
      icon: namespace
      required: true

  actions:
    - name: "Create manifest"
      gitops:
        commit:
          author: $(.user.name)
          email: $(.user.email | default "" )
          message: "chore: create namespace $(.params.name)"
        files:
          - path: "$(.git.kustomize.path)/namespaces/$(.params.name)/kustomization.yaml"
            content: |
              apiVersion: kustomize.config.k8s.io/v1beta1
              kind: Kustomization
              buildMetadata: [originAnnotations]
              resources:
                - namespace.yaml
          - path: $(.git.kustomize.path)/namespaces/$(.params.name)/namespace.yaml
            content: |
              apiVersion: v1
              kind: Namespace
              metadata:
                name: $(.params.name)
                annotations:
                  "mission-control/playbook": $(.playbook.name)
                  "mission-control/run": $(.run.id)
                  "mission-control/createdBy": $(.user.name)
        patches:
          - path:  $(.git.kustomize.file)
            yq: '.resources += "namespaces/$(.params.name)"'
        {{ include "git-pr" (list . "Create namespace $(.params.name)" ) | nindent 8}}
        repo:
          {{ omit .Values.git "branch" "url" "base" | toYaml | nindent 10 }}
          url: $(.git.git.url)
          {{- if .Values.createPullRequest}}
          branch: "deploy/$(.params.name)"
          base: $(.git.git.branch)
          {{- else }}
          branch: $(.git.git.branch)
          {{- end }}
