{{ if .Values.playbooks.edit -}}
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: kustomize-edit
spec:
  title: 'Edit'
  category: Flux
  icon: flux
  parameters:
    - default: 'chore: update $(.config.type)/$(.config.name)'
      label: Commit Message
      name: commit_message
    - default: $(.config.config | toJSON | neat | json | toYAML)
      label: ""
      name: yamlInput
      properties:
        size: large
      type: code
    - default: '$(.git.git.url)'
      label: Git Repo
      name: url
    - default: '$(.git.git.file)'
      label: File
      name: file

  configs:
    - labelSelector: 'kustomize.toolkit.fluxcd.io/name'

  actions:
    - name: Create Pull Request With Changes
      gitops:
        repo:
          {{ include "git-origin" . | nindent 10}}
          branch: edit-manifest-$(random.Alpha 8)
        commit:
          author: '$(.user.name)'
          email: '$(.user.email)'
          message: $(.params.commit_message)
        {{ include "git-pr" (list . "$(.params.commit_message)" ) | nindent 8}}
        patches:
          - path: '$(.params.file)'
            yq: |
              select(
                .kind=="$(.config.config | jq `.kind`)" and
                .metadata.name=="$(.config.config | jq `.metadata.name`)"
              ) |= $(.params.yamlInput | yaml | toJSON)

{{ end }}
