{{- if and .Values.playbooks.enabled .Values.playbooks.cleanupFailedPods }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: cleanup-failed-pod
spec:
  title: Cleanup Failed Pods
  icon: remove-trash
  category: Kubernetes
  description: Deletes all failed kubernetes pod
  configs:
    - types:
        - Kubernetes::Cluster
  actions:
    - name: Delete pods
      exec:
        script: >
          kubectl get pods -A --no-headers |
          grep -E 'Completed|Error|CrashLoopBackOff|ErrImagePull|ImagePullBackOff|ContainerStatusUnknown|CreateContainerConfigError|Evicted' |
          while read -r namespace pod _; do
              kubectl delete pod "$pod" --namespace="$namespace"
          done
{{- end}}