{{- if and .Values.playbooks.enabled .Values.playbooks.deletePod }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: delete-pod
spec:
  title: Delete Pod
  icon: delete
  category: Kubernetes
  description: Deletes the selected pod
  configs:
    - types:
        - Kubernetes::Pod
  actions:
    - name: Delete pod
      exec:
        script: |
          kubectl delete pod -n $(.config.tags.namespace) $(.config.name)
{{- end}}