{{- if and .Values.playbooks .Values.playbooks.edit_kubernetes_manifests.enabled }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: request-namespace-access-gitops
spec:
  configs:
    - types:
        - Kubernetes::Namespace
  title: Request Namespace Access (GitOps)
  category: Kubernetes
  description: Adds a Rolebinding to the given role in the selected Namespace
  parameters:
    - name: repo
      label: Repository URL
    - name: base_branch
      label: Base branch
    - name: connection
      label: Repository Auth connection
      default: "{{.Values.playbooks.edit_kubernetes_manifests.git_connection}}"
    - name: path
      label: Path of the file
      default: '$(.config.tags.cluster)/rolebinding-$(.config.name).yaml'
    - name: user
      label: Role Subject User
    - name: delay
      label: Expires after
      type: list
      properties:
        options:
          - label: "4 hours"
            value: '4h'
          - label: "8 hours"
            value: '8h'
          - label: "3 days"
            value: "3d"
          - label: "10 days"
            value: "10d"
          - label: "2 weeks"
            value: "14d"
          - label: "30 days"
            value: "30d"
          - label: "Indefinitely"
            value: "0"
    - name: role
      label: Role
      type: config
      properties:
        filter:
          - types:
              - Kubernetes::ClusterRole
  actions:
    - name: Create RoleBinding
      gitops:
        repo:
          url: '$(.params.repo)'
          connection: '$(.params.connection)'
          base: '$(.params.base_branch)'
          branch: 'request-namespace-access-$(.config.name)-$(.params.role.name)-$(.run.id)'
          type: 'github'
        commit:
          email: '$(.user.email)'
          author: '$(.user.name)'
          message: 'chore(rbac): grant $(.params.user) $(.params.role.name) on $(.config.name)'
        pr:
          title:  'Grant $(.params.user) $(.params.role.name) on $(.config.name)'
        files:
          - path: '$(.params.path)'
            content: |
              apiVersion: rbac.authorization.k8s.io/v1
              kind: RoleBinding
              metadata:
                name: "$(.params.role.name)-$(.run.id)
                namespace: default
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: Role
                name: $(.params.role.name)
              subjects:
                - apiGroup: rbac.authorization.k8s.io
                  kind: User
                  name: $(.params.user)
    - name: Clear Rolebinding
      if: 'success() && params.delay != "0"'
      delay: '.params.delay'
      gitops:
        repo:
          url: '$(.params.repo)'
          connection: '$(.params.connection)'
          base: '$(.params.base_branch)'
          branch: 'request-namespace-access-$(.config.name)-$(.params.role.name)-$(.run.id)'
        commit:
          email: '$(.user.email)'
          author: '$(.user.name)'
          message: 'chore(rbac): revoke $(.params.user) $(.params.role.name) on $(.config.name)'
        pr:
          title: 'Revoke $(.params.user) $(.params.role.name) on $(.config.name)'
        files:
          - path: '$(.params.path)'
            content: '$delete'
{{- end}}