{{- if and .Values.playbooks .Values.playbooks.edit_kubernetes_manifests.enabled }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: request-namespace-access-gitops
spec:
  configs:
    - types:
        - Kubernetes::Namespace
      labelSelector: 'kustomize.toolkit.fluxcd.io/name' # limits to namespaces created by flux
  title: Request Namespace Access (GitOps)
  category: Kubernetes
  icon: add-shield
  description: Adds a Rolebinding to the given role in the selected Namespace
  env:
    - name: file_path
      value: {{ "'{{" }} (.config.config | jq `.metadata.annotations["config.kubernetes.io/origin"]` | yaml).path {{ "}}'" }}
    - name: git_url
      value: {{ "'{{" }} (index (catalog_traverse .config.id "Kubernetes::Kustomization/Kubernetes::GitRepository" "incoming") 0).Config | json | jq `.spec.url` {{ "}}'" }}
    - name: git_branch
      value: {{ "'{{" }} (index (catalog_traverse .config.id "Kubernetes::Kustomization/Kubernetes::GitRepository" "incoming") 0).Config | json | jq `.spec.ref.branch` {{ "}}'" }}
    - name: kustomization_path
      value: {{ "'{{" }} (index (catalog_traverse .config.id "Kubernetes::Kustomization" "incoming") 0).Config | json | jq `.spec.path` {{ "}}'" }}
  parameters:
    - name: connection
      label: Repository Auth connection
      default: "{{.Values.playbooks.edit_kubernetes_manifests.git_connection}}"
    - name: user
      label: Role Subject User
    - name: delay
      label: Expires after
      type: list
      properties:
        options:
          - label: "4 hours"
            value: '4h'
          - label: "8 hours"
            value: '8h'
          - label: "3 days"
            value: "3d"
          - label: "10 days"
            value: "10d"
          - label: "2 weeks"
            value: "14d"
          - label: "30 days"
            value: "30d"
          - label: "Indefinitely"
            value: "0"
    - name: role
      label: Role
      type: config
      properties:
        filter:
          - types:
              - Kubernetes::ClusterRole
  actions:
    - name: Create RoleBinding
      gitops:
        repo:
          url: '$(.env.git_url)'
          connection: '$(.params.connection)'
          base: '$(.env.git_branch)'
          branch: 'grant-namespace-access-$(.run.id)'
        commit:
          email: '$(.user.email)'
          author: '$(.user.name)'
          message: 'chore(rbac): grant $(.params.user) $(.params.role.name) on $(.config.name)'
        pr:
          title: 'Grant $(.params.user) $(.params.role.name) on $(.config.name)'
        patches:
          - path: {{ "'{{" }} filepath.Join (filepath.Dir (filepath.Join .env.kustomization_path .env.file_path)) "kustomization.yaml" {{ "}}'" }}
            yq: .resources += "rolebinding-$(.config.name).yaml"
        files:
          - path: {{ "'{{" }} filepath.Join (filepath.Dir (filepath.Join .env.kustomization_path .env.file_path)) "rolebinding-$(.config.name).yaml" {{ "}}'" }}
            content: |
              apiVersion: rbac.authorization.k8s.io/v1
              kind: RoleBinding
              metadata:
                name: "$(.params.role.name)-$(.run.id)"
                namespace: default
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: Role
                name: $(.params.role.name)
              subjects:
                - apiGroup: rbac.authorization.k8s.io
                  kind: User
                  name: $(.params.user)
    - name: Clear Rolebinding
      if: 'success() && .params.delay != "0"'
      delay: '.params.delay'
      gitops:
        repo:
          url: '$(.env.git_url)'
          connection: '$(.params.connection)'
          base: '$(.env.git_branch)'
          branch: 'revoke-namespace-access-$(.run.id)'
        commit:
          email: '$(.user.email)'
          author: '$(.user.name)'
          message: 'chore(rbac): revoke $(.params.user) $(.params.role.name) on $(.config.name)'
        pr:
          title: 'Revoke $(.params.user) $(.params.role.name) on $(.config.name)'
        patches:
          - path: {{ "'{{" }} filepath.Join (filepath.Dir (filepath.Join .env.kustomization_path .env.file_path)) "kustomization.yaml" {{ "}}'" }}
            yq: .resources -= "del(.resources[] | select(. == "rolebinding-$(.config.name).yaml"))'"
        files:
          - path: '$(.env.kustomization_path)/rolebinding-$(.config.name).yaml'
            content: '$delete'
{{- end}}