{{ if and .Values.playbooks.enabled .Values.playbooks.fluxUpdateResourceResources.enabled -}}
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: gitops-update-resource-resources
spec:
  title: 'Update resource resources (GitOps)'
  icon: flux
  parameters:
  - default: 'chore: update resources for $(.config.type)/$(.config.name)'
    label: Commit Message
    name: commit_message
  - name: cpu_request
    label: CPU Request
    type: text
    default: '{{` {{ (index .config.config.spec.template.spec.containers 0).resources.requests.cpu | default "" }} `}}'
  - name: memory_request
    label: Memory Request
    type: text
    default: '{{` {{ (index .config.config.spec.template.spec.containers 0).resources.requests.memory | default "" }} `}}'
  - name: cpu_limit
    label: CPU Limit
    type: text
    default: '{{` {{ (index .config.config.spec.template.spec.containers 0).resources.limits.cpu | default "" }} `}}'
  - name: memory_limit
    label: Memory Limit
    type: text
    default: '{{` {{ (index .config.config.spec.template.spec.containers 0).resources.limits.memory | default "" }} `}}'

  configs:
    - labelSelector: 'kustomize.toolkit.fluxcd.io/name'
      types:
        - Kubernetes::Deployment
        - Kubernetes::StatefulSet
        - Kubernetes::DaemonSet

  actions:
    - name: Create Pull Request With Changes
      gitops:
        repo:
          url: '$(.env.git.url)'
          connection: {{ .Values.playbooks.edit_kubernetes_manifests.git_connection }}
          base: '$(.env.git.branch)'
          branch: edit-manifest-$(random.Alpha 8)
        commit:
          author: '$(.user.name)'
          email: '$(.user.email)'
          message: $(.params.commit_message | strings.ReplaceAll "<new_image>" .params.image)
        pr:
          title: $(.params.commit_message | strings.ReplaceAll "<new_image>" .params.image)
        patches:
          - path: '$(filepath.Join .env.kustomize.path .env.git.file)'
            yq: |
              select(
                .kind=="$(.config.config | jq `.kind`)" and
                .metadata.name=="$(.config.config | jq `.metadata.name`)"
              ).spec.template.spec.containers[0].resources |= {
                "requests": {"cpu": "$(.params.cpu_request)", "memory": $(.params.memory_request)},
                "limits": {"cpu": "$(.params.cpu_limit)", "memory": $(.params.memory_limit)}
              }
{{ end }}
