{{- if and .Values.playbooks.enabled .Values.playbooks.requestNamespaceAccess }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: request-namespace-access
spec:
  title: Request Namespace Access
  icon: add-shield
  category: Kubernetes
  description: Adds a Rolebinding to the given role
  parameters:
    - name: user
      label: User
    - name: delay
      label: Expires after
      type: list
      properties:
        options:
          - label: "30 minutes"
            value: '30m'
          - label: "1 hour"
            value: '1h'
          - label: "6 hour"
            value: "6h"
          - label: "12 hours"
            value: "12h"
          - label: "1 day"
            value: "1d"
          - label: "1 week"
            value: "1w"
    - name: role
      label: Role
      type: config
      properties:
        filter:
          - types:
              - Kubernetes::ClusterRole
  configs:
    - types:
        - Kubernetes::Namespace
  actions:
    - name: Create RoleBinding
      exec:
        script: >-
          kubectl create rolebinding "playbook-$(.run.id)"
          --namespace=$(.config.name)
          --user=$(.params.user)
          --role=$(.params.role.name)
    - name: Clear Rolebinding
      if: "success()"
      delay: ".params.delay"
      exec:
        script: |
          kubectl delete rolebinding "playbook-$(.run.id)" --namespace=$(.config.name)
{{- end}}