{{- if and .Values.playbooks.enabled .Values.playbooks.restartDeployment }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: restart-deployment
spec:
  title: Restart Deployment
  icon: reload
  category: Kubernetes
  configs:
    - types:
        - Kubernetes::Deployment
  actions:
    - name: Scale deployment
      exec:
        script: kubectl rollout release deployment -n $(.config.tags.namespace) $(.config.name)
{{- end}}