{{- if and .Values.playbooks.enabled .Values.playbooks.updateResourceImage }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: update-resource-image
spec:
  title: Update image
  icon: k8s-deployment
  category: Kubernetes
  configs:
    - types:
        - Kubernetes::Deployment
        - Kubernetes::StatefulSet
        - Kubernetes::DaemonSet
  parameters:
    - name: image
      label: Image
      type: text
      default: '{{ "{{" }} (index .config.config.spec.template.spec.containers 0 ).image {{ "}}" }}'
  actions:
    - name: Update image
      exec:
        script: |
          kubectl set image -n $(.config.tags.namespace) $(.config.config_class | strings.ToLower)/$(.config.name) {{ "{{" }} ( index .config.config.spec.template.spec.containers 0 ).name {{ "}}" }}=$(.params.image)
{{- end}}
