{{- if and .Values.views.enabled .Values.views.clusterOverview.enabled .Values.global.prometheus.connection }}
apiVersion: mission-control.flanksource.com/v1
kind: View
metadata:
  name: cluster-overview
  labels:
    {{- include "kubernetes-view.labels" . | nindent 4 }}
spec:
  cache:
    refreshTimeout: 30s
  templating:
    - key: cluster
      label: Cluster
      valueFrom:
        config:
          agent: "all"
          types:
            - Kubernetes::Cluster
  display:
    title: Cluster
    icon: kubernetes::cluster
    {{- if .Values.views.clusterOverview.sidebar }}
    sidebar: true
    {{- end }}
    table:
      sort: name
      size: 10
    plugins:
      - configTab:
          types:
            - Kubernetes::Cluster
  panels:
    - name: Resources
      description: Count of resources grouped by type
      type: table
      query: SELECT * FROM resource_count_by_type
    {{- if .Values.views.nodes.enabled }}
    - name: CPU Usage
      type: gauge
      query: |
        SELECT SUM(cpu) AS value
        FROM node_overview
        WHERE cluster IN (SELECT DISTINCT cluster FROM namespaces)
          AND cpu IS NOT NULL
        HAVING COUNT(cpu) > 0
      gauge:
        unit: millicore
        max: >-
          size(.dataset.namespaces) > 0 && size(.dataset.node_overview) > 0 ?
          .dataset.node_overview
            .filter(node, has(node.allocatable_cpu) && node.allocatable_cpu != null && node.cluster == .dataset.namespaces[0].cluster)
            .map(node, double(node.allocatable_cpu))
            .sum() : 0.0
        thresholds:
          - percent: 0
            color: '#28C19B'
          - percent: 70
            color: '#F4B23C'
          - percent: 85
            color: '#F25C54'
    - name: Memory Usage
      type: gauge
      query: |
        SELECT SUM(memory) AS value
        FROM node_overview
        WHERE cluster IN (SELECT DISTINCT cluster FROM namespaces)
          AND memory IS NOT NULL
        HAVING COUNT(memory) > 0
      gauge:
        max: >-
          size(.dataset.namespaces) > 0 && size(.dataset.node_overview) > 0 ?
          .dataset.node_overview
            .filter(node, has(node.allocatable_memory) && node.allocatable_memory != null && node.cluster == .dataset.namespaces[0].cluster)
            .map(node, double(node.allocatable_memory))
            .sum() : 0.0
        unit: bytes
        thresholds:
          - percent: 0
            color: '#28C19B'
          - percent: 70
            color: '#F4B23C'
          - percent: 85
            color: '#F25C54'
    {{- end }}
    - name: Pods Node Distribution
      description: Distribution of pods across nodes
      type: piechart
      piechart:
        showLabels: true
      query: SELECT value as "count", node FROM pods_node_distribution
    {{- if .Values.views.nodes.enabled }}
    - name: Memory Real Usage
      type: bargauge
      query: |
        SELECT 'Real' AS name, ROUND(SUM(memory), 1) AS value
        FROM node_overview
        WHERE cluster IN (SELECT DISTINCT cluster FROM namespaces)
          AND memory IS NOT NULL
        HAVING COUNT(memory) > 0
      bargauge:
        group: "Memory"
        max: >-
          size(.dataset.namespaces) > 0 && size(.dataset.node_overview) > 0 ?
          .dataset.node_overview
            .filter(node, has(node.allocatable_memory) && node.allocatable_memory != null && node.cluster == .dataset.namespaces[0].cluster)
            .map(node, double(node.allocatable_memory))
            .sum() : 0.0
        unit: bytes
        thresholds:
          - percent: 0
            color: '#28C19B'
          - percent: 70
            color: '#F4B23C'
          - percent: 80
            color: '#F25C54'
    {{- end }}
    - name: Memory Requests
      type: bargauge
      query: |
        SELECT 'Requests' as name, ROUND(value, 1) as value FROM memory_request
      bargauge:
        group: "Memory"
        max: "size(.dataset.total_machine_memory) > 0 ? .dataset.total_machine_memory[0].value : 0"
        unit: bytes
        format: percentage
        thresholds:
          - percent: 0
            color: '#F25C54'
          - percent: 30
            color: '#F4B23C'
          - percent: 70
            color: '#28C19B'
          - percent: 100
            color: '#F25C54'
    - name: Memory Limits
      type: bargauge
      query: |
        SELECT 'Limits' as name, ROUND(value, 1) as value FROM memory_limit
      bargauge:
        group: "Memory"
        max: "size(.dataset.total_machine_memory) > 0 ? .dataset.total_machine_memory[0].value : 0"
        unit: bytes
        format: multiplier
        thresholds:
          - percent: 0
            color: '#F25C54'
          - percent: 30
            color: '#F4B23C'
          - percent: 100
            color: '#28C19B'
          - percent: 400
            color: '#F25C54'  
    {{- if .Values.views.nodes.enabled }}
    - name: CPU Real Usage
      type: bargauge
      query: |
        SELECT 'Real' AS name, ROUND(SUM(cpu), 1) AS value
        FROM node_overview
        WHERE cluster IN (SELECT DISTINCT cluster FROM namespaces)
          AND cpu IS NOT NULL
        HAVING COUNT(cpu) > 0
      bargauge:
        group: "CPU"
        max: >-
          size(.dataset.namespaces) > 0 && size(.dataset.node_overview) > 0 ?
          .dataset.node_overview
            .filter(node, has(node.allocatable_cpu) && node.allocatable_cpu != null && node.cluster == .dataset.namespaces[0].cluster)
            .map(node, double(node.allocatable_cpu))
            .sum() : 0.0
        unit: millicores
        thresholds:
          - percent: 0
            color: '#28C19B'
          - percent: 70
            color: '#F4B23C'
          - percent: 80
            color: '#F25C54'
    {{- end }}
    - name: CPU Requests
      type: bargauge
      query: |
        SELECT 'Requests' as name, ROUND(value, 1) as value FROM cpu_request
      bargauge:
        group: "CPU"
        max: "size(.dataset.total_cpu) > 0 ? .dataset.total_cpu[0].value : 0"
        unit: millicores
        format: percentage
        thresholds:
          - percent: 0
            color: '#F25C54'
          - percent: 30
            color: '#F4B23C'
          - percent: 70
            color: '#28C19B'
          - percent: 100
            color: '#F25C54'
    - name: CPU Limits
      type: bargauge
      query: |
        SELECT 'Limits' as name, ROUND(value, 1) as value FROM cpu_limit
      bargauge:
        group: "CPU"
        max: "size(.dataset.total_cpu) > 0 ? .dataset.total_cpu[0].value : 0"
        unit: millicores
        format: multiplier
        thresholds:
          - percent: 0
            color: '#F25C54'
          - percent: 30
            color: '#F4B23C'
          - percent: 100
            color: '#28C19B'
          - percent: 400
            color: '#F25C54'  
  columns:
    - name: id
      type: string
      hidden: true
      primaryKey: true
    - name: name
      type: config_item
      width: "4"
      card:
        position: title
      url:
        view:
          filter:
            viewvar__namespace: row.name
            viewvar__cluster: row.cluster
          name: >
            'namespace'
    - name: cpu_usage
      type: gauge
      width: "2"
      unit: millicore
      description: CPU usage
      card:
        position: headerRight
      gauge:
        max: row.cpu_limit
        thresholds:
          - percent: 0
            color: '#28C19B'
          - percent: 70
            color: '#F4B23C'
          - percent: 85
            color: '#F25C54'
    - name: memory_usage
      type: gauge
      width: "2"
      unit: bytes
      card:
        position: headerRight
      description: Memory usage
      gauge:
        max: row.memory_limit
        thresholds:
          - percent: 0
            color: '#28C19B'
          - percent: 75
            color: '#F4B23C'
          - percent: 90
            color: '#F25C54'
    - name: pods
      type: number
      width: "1"
      card:
        position: body
      description: Total number of running pods
    - name: created_at
      type: datetime
      width: "2"
      card:
        position: footer
  merge: |
    SELECT
      namespaces.id,
      namespaces.name,
      json_extract(namespaces.tags, '$.cluster') AS cluster,
      namespaces.created_at,
      cpu_usage_by_namespace.value AS cpu_usage,
      memory_usage_by_namespace.value AS memory_usage,
      cpu_limit_by_namespace.value AS cpu_limit,
      memory_limit_by_namespace.value AS memory_limit,
      pod_count_by_namespace.value AS pods
    FROM namespaces
    LEFT JOIN cpu_usage_by_namespace
      ON namespaces.name = cpu_usage_by_namespace.namespace
    LEFT JOIN memory_usage_by_namespace
      ON namespaces.name = memory_usage_by_namespace.namespace
    LEFT JOIN cpu_limit_by_namespace
      ON namespaces.name = cpu_limit_by_namespace.namespace
    LEFT JOIN memory_limit_by_namespace
      ON namespaces.name = memory_limit_by_namespace.namespace
    LEFT JOIN pod_count_by_namespace
      ON namespaces.name = pod_count_by_namespace.namespace
    ORDER BY name
  queries:
    cpu_usage_by_namespace:
      columns:
        namespace: string
        value : decimal
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum by (namespace) (
            irate(container_cpu_usage_seconds_total{
              container!="POD",
              container!=""
            }[5m])
          ) * 1000
    memory_usage_by_namespace:
      columns:
        namespace: string
        value: decimal
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum by (namespace) (
            container_memory_working_set_bytes{
              container!="POD",
              container!=""
            }
          )
    cpu_limit_by_namespace:
      columns:
        namespace: string
        value: decimal
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum by (namespace) (
            (
              kube_pod_container_resource_limits{resource="cpu", container!="POD", container!=""} > 0
            ) or
            kube_pod_container_resource_requests{resource="cpu", container!="POD", container!=""}
          ) * 1000
    memory_limit_by_namespace:
      columns:
        namespace: string
        value: decimal
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum by (namespace) (
            (
              kube_pod_container_resource_limits{resource="memory", container!="POD", container!=""} > 0
            ) or
            kube_pod_container_resource_requests{resource="memory", container!="POD", container!=""}
          )
    pod_count_by_namespace:
      columns:
        namespace: string
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          count(kube_pod_status_phase{phase="Running"}) by (namespace)
    pods_node_distribution:
      columns:
        node: string
        value: decimal
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          count(kube_pod_info) by (node)
    total_cpu:
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum(machine_cpu_cores{}) * 1000
    resource_count_by_type:
      columns:
        resource_type: string
        value: decimal
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          (label_replace(count(kube_node_info), "resource_type", "Nodes", "", "")) or 
          (label_replace(count(kube_namespace_status_phase{phase="Active"}), "resource_type", "Namespaces", "", "")) or 
          (label_replace(count(kube_pod_status_phase{phase="Running"}), "resource_type", "Running Pods", "", "")) or 
          (label_replace(count(kube_deployment_status_replicas), "resource_type", "Deployments", "", "")) or 
          (label_replace(count(kube_statefulset_status_replicas), "resource_type", "StatefulSets", "", "")) or 
          (label_replace(count(kube_daemonset_status_number_ready), "resource_type", "DaemonSets", "", "")) or 
          (label_replace(count(kube_persistentvolume_info), "resource_type", "Persistent Volumes", "", "")) or 
          (label_replace(count(kube_persistentvolumeclaim_info), "resource_type", "Persistent Volume Claims", "", "")) or
          (label_replace(count(kube_ingress_info), "resource_type", "Ingresses", "", "")) or
          (label_replace(count(kube_cronjob_info), "resource_type", "CronJobs", "", ""))
    cpu_request:
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum(kube_pod_container_resource_requests{resource="cpu"}) * 1000
    cpu_limit:
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum(kube_pod_container_resource_limits{resource="cpu"}) * 1000
    memory_request:
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum(kube_pod_container_resource_requests{resource="memory"})
    memory_limit:
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum(kube_pod_container_resource_limits{resource="memory"})
    total_machine_memory:
      prometheus:
        connection: {{ .Values.global.prometheus.connection }}
        query: |
          sum(machine_memory_bytes{})
    namespaces:
      configs:
        tagSelector: "cluster=$(.var.cluster)"
        agent: "all"
        types:
          - Kubernetes::Namespace
    {{- if .Values.views.nodes.enabled }}
    node_overview:
      columns:
        id: string
        name: string
        cluster: string
        status: string
        health: string
        created_at: datetime
        cpu: decimal
        memory: decimal
        disk: decimal
        pods: decimal
        allocatable_cpu: decimal
        allocatable_memory: decimal
        role: string
        zone: string
        uptime: duration
        load: decimal
        __row__attributes: jsonb
        __grants: jsonb
        request_fingerprint: string
        agent_id: string
        is_pushed: boolean
      viewTableSelector:
        name: nodes
        namespace: {{ .Release.Namespace }}
    {{- end }}
{{- end }}