apiVersion: v2
name: mission-control-postgres
description: A Helm chart to deploy postgres statefulset with a Mission Control Playbook
icon: https://github.com/flanksource/docs/blob/main/docs/images/flanksource-icon.png?raw=true
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Flanksource
