# yaml-language-server: $schema=values.schema.json
nameOverride: ""
fullnameOverride: ""
labels: {}

scraper:
  name: "helm-chart-scraper"
  schedule: "@every 1d"

  # @schema
  # required: true
  # type: array
  # items:
  #   type: string
  # @schema
  charts:
    - flanksource/mission-control-agent
    - flanksource/mission-control-argocd
    - flanksource/mission-control-flux
    - flanksource/mission-control-aws
    - flanksource/mission-control-azure
    - flanksource/mission-control-flux
    - flanksource/mission-control-mongo-atlas
    - flanksource/mission-control-playbooks-flux
    - flanksource/mission-control-playbooks-kubernetes
    - flanksource/mission-control-playbooks-ai
    - flanksource/mission-control-postgres
    - flanksource/mission-control-prometheus
    - bitnami/postgresql
    - bitnami/postgresql-ha
    - bitnami/mysql
    - bitnami/rabbitmq
    - bitnami/kafka
    - bitnami/mongodb
    - bitnami/keycloak
    - bitnami/minio
    - bitnami/opensearch
    - bitnami/jaeger
    - bitnami/harbor
    - bitnami/memcached
    - bitnami/cert-manager
    - bitnami/external-secrets
    - bitnami/clickhouse
    - bitnami/jupyterhub
    - bitnami/grafana-operator
    - bitnami/argo-cd
    - bitnami/sonarqube
    - bitnami/oauth2-proxy

# @schema
# required: false
# type: object
# @schema
git:
  # @schema
  # required: false
  # type: string
  # @schema
  connection: ""

  # @schema
  # required: false
  # type: string
  # @schema
  url: ""

  # @schema
  # required: false
  # type: string
  # @schema
  # url: https://github.com/flanksource/demo-gitops.git
  type: github

# install a playbook that allows installation of scraped helm charts into a namespace
playbook:
  # @schema
  # required: false
  # type: boolean
  # @schema
  enabled: true

  name: "install-helm-chart"
