# yaml-language-server: $schema=values.schema.json
nameOverride: ""
fullnameOverride: ""
labels: {}

scraper:
  name: "helm-chart-scraper"
  schedule: "@every 1d"

  # @schema
  # required: true
  # type: array
  # items:
  #   type: string
  # @schema
  charts: []

# @schema
# required: false
# type: object
# @schema
git:
  # @schema
  # required: false
  # type: string
  # @schema
  connection: ""

  # @schema
  # required: false
  # type: string
  # @schema
  url: ""

  # @schema
  # required: false
  # type: string
  # @schema
  # url: https://github.com/flanksource/demo-gitops.git
  type: github

# install a playbook that allows installation of scraped helm charts into a namespace
playbook:
  # @schema
  # required: false
  # type: boolean
  # @schema
  enable: true

  name: "install-helm-chart"
