# yaml-language-server: $schema=https://raw.githubusercontent.com/flanksource/duty/main/schema/openapi/playbook.schema.json
{{- if .Values.diagnose.enabled }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Playbook
metadata:
  name: ai-diagnose
spec:
  description: Diagnoses the health of a resource using AI{{- if .Values.slack.connection}}, optionally sending the result to Slack{{- end}}
  title: Diagnose
  icon: bot
  category: AI
  configs:
    {{- with .Values.diagnose.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  parameters:
    - name: prompt
      label: Prompt
      default: 'Find out why $(.config.name) is unhealthy'
      properties:
        multiline: 'true'
    {{- if .Values.slack.connection}}
    - name: slack
      type: checkbox
      label: Send result to Slack
    {{- end }}

  actions:
    - name: diagnose with AI
      timeout: 10m
      ai:
        connection: '{{.Values.global.llm_connection}}'
        systemPrompt: '{{.Values.diagnose.notification.systemPrompt}}'
        prompt: '$(.params.prompt)'
        {{- if .Values.slack.connection}}
        formats:
          - slack
        {{- end }}
        changes:
          since: {{.Values.diagnose.timeframe.changes}}
        analysis:
          since: {{.Values.diagnose.timeframe.analysis}}
        relationships:
          - depth: 5
            direction: all
            changes:
              since: {{.Values.diagnose.timeframe.relatedChanges}}
            analysis:
              since: {{.Values.diagnose.timeframe.relatedAnalysis}}
  {{- if .Values.slack.connection}}
    - name: send result
      if: success() && bool(params.slack)
      notification:
        connection: {{.Values.slack.connection}}
        message: "$(getLastAction.result.slack)"
        title: Diagnosis report
    {{/*
      - name: send failure message
      if: failure() && bool(params.slack)
      notification:
        connection: {{.Values.slack.connection}}
        message: |
          {
            "blocks": [
              $(slackSectionTextMD (printf `%s AI analysis failed for $(.config.name)` (slackHealthEmoji "unhealthy")))
              {"type": "divider"},
              $(slackSectionTextPlain getLastAction.result.error),
              $(slackSectionLabels .config.labels),
              $(slackURLAction .config.name .permalink)
            ]
          }
        title: Diagnosis report */}}
  {{- end }}
{{- end}}
