{{- if and .Values.diagnose.enabled .Values.diagnose.playbooksRecommender.enabled .Values.diagnose.playbooksRecommender.notification.create }}
---
apiVersion: mission-control.flanksource.com/v1
kind: Notification
metadata:
  name: notify-recommender-playbook
spec:
  events:
    {{- with .Values.diagnose.playbooksRecommender.notification.events }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  to:
    playbook: {{.Release.Namespace}}/recommend-playbook
  {{- if .Values.diagnose.playbooksRecommender.notification.waitFor}}
  waitFor: {{.Values.diagnose.playbooksRecommender.notification.waitFor}}
  {{- end}}
  {{- if .Values.diagnose.playbooksRecommender.notification.repeatInterval}}
  repeatInterval: {{.Values.diagnose.playbooksRecommender.notification.repeatInterval}}
  {{- end}}
  {{- with .Values.diagnose.playbooksRecommender.notification.inhibitions}}
  inhibitions:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- with .Values.diagnose.playbooksRecommender.notification.groupBy}}
  groupBy: 
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- if .Values.diagnose.playbooksRecommender.notification.filter}}
  filter: {{.Values.diagnose.playbooksRecommender.notification.filter}}
  {{- end}}
  {{- if .Values.diagnose.playbooksRecommender.notification.waitForEvalPeriod}}
  waitForEvalPeriod: {{.Values.diagnose.playbooksRecommender.notification.waitForEvalPeriod}}
  {{- end}}
  {{- if .Values.slack.connection}}
  fallback:
    connection: {{.Values.slack.connection}}
  {{- end}}
---
apiVersion: mission-control.flanksource.com/v1
kind: Permission
metadata:
  name: allow-notify-recommender-playbook-run
spec:
  description: allow notification "notify-recommender-playbook" to run the AI playbook recommender playbook
  subject:
    notification: "{{.Release.Namespace}}/notify-recommender-playbook"
  actions:
    - playbook:*
  object:
    playbooks:
      - name: recommend-playbook
        namespace: {{.Release.Namespace}}
    configs:
      - name: "*"
---
apiVersion: mission-control.flanksource.com/v1
kind: Permission
metadata:
  name: allow-notify-recommender-connection-read
spec:
  description: allow notification "notify-recommender-playbook" to read slack connection
  subject:
    notification: "{{.Release.Namespace}}/notify-recommender-playbook"
  actions:
    - read
  object:
    connections:
      {{- with include "parse-connection" .Values.slack.connection }}
      {{- $connection := . | fromYaml }}
      - name: {{ $connection.name | quote }}
        namespace: {{ $connection.namespace | quote }}
      {{- end }}
{{- end }}
